// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Q7gvfj-nmYBNYmvt3RDy2trYgiQMAGQ',
    appId: '1:92755572585:web:9bed60377d2258526b2ff8',
    messagingSenderId: '92755572585',
    projectId: 'distriserviciosapp2-f3969',
    authDomain: 'distriserviciosapp2-f3969.firebaseapp.com',
    storageBucket: 'distriserviciosapp2-f3969.appspot.com',
    measurementId: 'G-C76HYYT1MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2qdmUQUkEMspmcwNAfNpBCAMmZv6HfMo',
    appId: '1:92755572585:android:cd32775602e467706b2ff8',
    messagingSenderId: '92755572585',
    projectId: 'distriserviciosapp2-f3969',
    storageBucket: 'distriserviciosapp2-f3969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUN30B-P4lXhMF6YbznTF6IZgNYqpsys',
    appId: '1:92755572585:ios:7627599e16f223546b2ff8',
    messagingSenderId: '92755572585',
    projectId: 'distriserviciosapp2-f3969',
    storageBucket: 'distriserviciosapp2-f3969.appspot.com',
    iosBundleId: 'com.example.distriserviciosApp2',
  );
}
